### PR TITLE
Layers commands

### PR DESCRIPTION
**Pull request by Lurgainn**
I moved large chunks of code from "main" into separate functions in optic of reusability (for example, if config file is modified while the program is running, it can be reloaded to immediately change the settings).
Then I introduced the possibility to specify commands to be executed when you swap layers. If a command is present, it'll be executed, but if itsn't, it'll be ignored, so the program continue to be able to use old config.json files without layers commands.

### CODE REVIEW

**Comment by sebastiansam55** [comment]
Can you please include an example of the config layout with these changes and update the readme accordingly?

**Comment by Lurgainn** [comment]
> Can you please include an example of the config layout with these changes and update the readme accordingly?

Sure: I'll do and when I'm finished I'll notify you.

**Comment by Lurgainn** [comment]
> Can you please include an example of the config layout with these changes and update the readme accordingly?

Done. In my repository I added tag "v0.2" too. I don't know if tags too are synchronized in pull requests/merge.
Anyway let me know if you are ok with these chenges and you merge them.

**Comment by sebastiansam55** [comment]
doesn't look like the tag carried over after the PR

**Comment by Lurgainn** [comment]
> doesn't look like the tag carried over after the PR

Then, if you want, you can apply yourself on your main branch. I did it with the command git tag -a v0.2 -m "Version 0.2"

**Pull request merged**
